language: java
sudo: required
services:
  - docker
jdk:
  - oraclejdk8
notifications:
  email: false

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - "mvn dockerfile:build"
  - "mvn dockerfile:push"